openapi: 3.0.2
info:
  contact:
    name: IXON B.V.
    url: https://www.ixon.cloud/
    email: support@ixon.cloud
  description: API for the IXON Cloud Platform
  license:
    name: All Rights Reserved
    url: https://www.ixon.cloud/
  title: IXON AccessRecoverList MyAccessRecoverFinish API
  version: 0.1.294
servers:
- description: IXON Cloud platform server
  url: https://portal.ixon.cloud:443/api/
tags:
- name: MyAccessRecoverFinish
paths:
  /access-recover/me/finish:
    post:
      tags:
      - MyAccessRecoverFinish
      summary: MyAccessRecoverFinish
      responses:
        '201':
          description: Success response
          content:
            application/json:
              schema:
                type: object
                required:
                - status
                - type
                - data
                properties:
                  status:
                    type: string
                    default: success
                    nullable: false
                  type:
                    type: string
                    nullable: false
                  data:
                    type: object
                    nullable: true
      parameters:
      - $ref: '#/components/parameters/apiVersion'
      - $ref: '#/components/parameters/apiApplication'
      - $ref: '#/components/parameters/apiBrandingRequired'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newPassword:
                  minLength: 8
                  nullable: false
                  type: string
                deleteAccessTokens:
                  nullable: false
                  type: boolean
              required:
              - newPassword
              - deleteAccessTokens
components:
  parameters:
    apiBrandingRequired:
      required: true
      description: Domain that provides the branding
      name: Api-Branding
      in: header
      schema:
        type: string
        pattern: .+(\..[^.]+)
    apiVersion:
      required: true
      description: Version of the API to use
      name: Api-Version
      in: header
      schema:
        type: integer
        format: int32
        enum:
        - 2
    apiApplication:
      required: true
      description: Get your Application ID via support@ixon.cloud
      name: Api-Application
      in: header
      schema:
        type: string
        pattern: ^[0-9a-zA-Z]{12}$
  securitySchemes:
    bearerToken:
      type: http
      description: Bearer token created by the endpoint "POST AccessTokenList"
      scheme: bearer
x-samples-languages:
- curl
- ruby
- javascript
- python
- powershell
